services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\SinaWeiboOAuth2Bundle\Service\:
    resource: '../../Service/'
  Tourze\SinaWeiboOAuth2Bundle\Repository\:
    resource: '../../Repository/'
  Tourze\SinaWeiboOAuth2Bundle\Controller\:
    resource: '../../Controller/'
  Tourze\SinaWeiboOAuth2Bundle\Command\:
    resource: '../../Command/'
  Tourze\SinaWeiboOAuth2Bundle\Factory\:
    resource: '../../Factory/'
