services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  # Services
  Tourze\SinaWeiboOAuth2Bundle\Service\:
    resource: '../../Service/'

  # Repositories
  Tourze\SinaWeiboOAuth2Bundle\Repository\:
    resource: '../../Repository/'

  # Controllers
  Tourze\SinaWeiboOAuth2Bundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  # Commands
  Tourze\SinaWeiboOAuth2Bundle\Command\:
    resource: '../../Command/'
    tags: ['console.command']

  # Repository service aliases for testing
  sina_weibo_oauth2.config_repository:
    alias: Tourze\SinaWeiboOAuth2Bundle\Repository\SinaWeiboOAuth2ConfigRepository
    public: true

  sina_weibo_oauth2.state_repository:
    alias: Tourze\SinaWeiboOAuth2Bundle\Repository\SinaWeiboOAuth2StateRepository
    public: true

  sina_weibo_oauth2.user_repository:
    alias: Tourze\SinaWeiboOAuth2Bundle\Repository\SinaWeiboOAuth2UserRepository
    public: true
