services:
  _defaults:
    autowire: true
    autoconfigure: true
    
  Tourze\SinaWeiboOAuth2Bundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'